openapi: 3.0.0
info:
  title: Backend Tienda API
  version: 1.0.0
  description: API migrada a AWS Lambda (serverless)
servers:
  - url: https://your-api-id.execute-api.us-east-1.amazonaws.com/dev
paths:
  /admin/login:
    post:
      summary: Login de administrador
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login exitoso
        '401':
          description: Credenciales inválidas
  /admin/register:
    post:
      summary: Registrar administrador
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Administrador registrado
        '400':
          description: Error de validación
  /admin/{id}/active:
    patch:
      summary: Activar/desactivar admin
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                activo:
                  type: boolean
      responses:
        '200':
          description: Estado actualizado
        '400':
          description: Error de validación
        '404':
          description: Admin no encontrado
  /admin/{id}/fecha-expiracion:
    patch:
      summary: Cambiar fecha de expiración
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fechaExpiracion:
                  type: string
                  format: date-time
      responses:
        '200':
          description: Fecha actualizada
        '400':
          description: Error de validación
        '404':
          description: Admin no encontrado
  /admin/{id}:
    delete:
      summary: Eliminar admin
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Admin eliminado
        '404':
          description: Admin no encontrado
  /admin/change-password:
    post:
      summary: Cambiar contraseña
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                newPassword:
                  type: string
      responses:
        '200':
          description: Contraseña cambiada
        '400':
          description: Error de validación
  /products:
    get:
      summary: Listar productos
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: categoria
          schema:
            type: string
        - in: query
          name: destacado
          schema:
            type: boolean
        - in: query
          name: minPrice
          schema:
            type: number
        - in: query
          name: maxPrice
          schema:
            type: number
      responses:
        '200':
          description: Lista de productos
    post:
      summary: Crear producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                categoria:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Producto creado
        '400':
          description: Error de validación
  /products/{id}:
    get:
      summary: Obtener producto por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto encontrado
        '404':
          description: Producto no encontrado
    put:
      summary: Actualizar producto
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Producto actualizado
        '400':
          description: Error de validación
        '404':
          description: Producto no encontrado
    delete:
      summary: Eliminar producto
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado
        '404':
          description: Producto no encontrado
  /comments:
    post:
      summary: Agregar comentario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                nombre:
                  type: string
                calificacion:
                  type: integer
                comentario:
                  type: string
      responses:
        '201':
          description: Comentario creado
        '400':
          description: Error de validación
  /comments/product/{productId}:
    get:
      summary: Listar comentarios de producto
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: Lista de comentarios
  /comments/product/{productId}/stats:
    get:
      summary: Estadísticas de calificaciones
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Estadísticas
  /clicks:
    post:
      summary: Registrar click
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
      responses:
        '201':
          description: Click registrado
        '400':
          description: Error de validación
    get:
      summary: Listar clicks
      responses:
        '200':
          description: Lista de clicks
  /clicks/by-product:
    get:
      summary: Estadísticas de clicks por producto
      responses:
        '200':
          description: Estadísticas por producto
